package com.example.test_proiect;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DefaultItemAnimator;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import java.util.ArrayList;

public class LegendeUrbaneActivity extends AppCompatActivity {
    private ArrayList<Obiect> objsList;
    private RecyclerView recyclerView;
    private recyclerAdapterlu.RecyclerViewClickListener listener;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_legende_urbane);
        recyclerView = findViewById(R.id.recyclerViewlu);
        objsList = new ArrayList<>();

        setObiectInfo();
        setAdapter();
    }

    private void setAdapter(){
        setOnClickListener();
        recyclerAdapterlu adapter = new recyclerAdapterlu(objsList, listener);
        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(getApplicationContext());
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setItemAnimator(new DefaultItemAnimator());
        recyclerView.setAdapter(adapter);
    }

    private void setOnClickListener() {
        listener = new recyclerAdapterlu.RecyclerViewClickListener() {
            @Override
            public void onClick(View v, int position) {
                Intent intent = new Intent(getApplicationContext(), ProfileActivity.class);
                intent.putExtra("titlu", objsList.get(position).getObj());
                intent.putExtra("imagine", objsList.get(position).getImagine());
                intent.putExtra("descriere", objsList.get(position).getDescriere());
                startActivity(intent);
            }
        };
    }


    private void setObiectInfo(){
        objsList.add(new Obiect("Pădurea Hoia-Baciu, Cluj ", R.drawable.lu1,"Pădurea Hoia-Baciu este unul dintre cele mai faimoase locuri din lume în care se înregistrează fenomene paranormale. Fie că te impresionează legendele şi misterele care s-au adunat în jurul ciudatei păduri sau, dimpotrivă, consideri că e o pădure ca oricare alta, locul este suficient de pitoresc pentru a merita atenţie din punct de vedere turistic şi recreaţional. Pădurea, aflată pe unul dintre dealurile ce înconjoară Clujul, a devenit faimoasă începând cu anii ’60, de când au început să fie semnalate tot felul de întâmplări cu strigoi şi alte apariţii inexplicabile în fotografii şi insesizabile cu ochiul liber, cu OZN-uri şi senzaţii auditive ciudate, cu stări anxioase şi senzaţia că ai fi urmărit.\n" +
                "Cele mai frecvente anomalii care au fost semnalate în pădurea Hoia-Baciu de-a lungul timpului sunt problemele cu echipamentele electronice (baterii care se descarcă neobişnuit de repede, restartări de telefoane, probleme cu GPS-ul, dificultăţi în configurarea frecvenţelor de sunet pentru înregistrări audio-video). Dincolo de legende, copacii sunt renumiţi pentru formele lor neobişnuite, iar Poiana Rotundă poate fi dacă nu un loc paranormal, un spaţiu de revenire la centrul interior, de regăsire în mijlocul naturii.\n"));
        objsList.add(new Obiect("Pădurea Radovan, Dolj ", R.drawable.lu2,"Localnicii din comuna doljeană Radovan îşi fac cruce în momentul în care sunt întrebaţi de fantoma din pădure. În urmă cu mai bine de 60 de ani, o tânără gonită din Moldova de sărăcie s-a spânzurat. De atunci, „Mireasa din Radovan“, imediat după lăsarea întunericului, le apare oamenilor în faţă. Oamenii din Radovan povestesc că tânăra Ileana a plecat din Moldova în căutarea unui trai mai bun. S-a angajat la un bărbat bogat din Radovan, care a început imediat să îi facă ochi dulci. Fata nu a cedat avansurilor, însă a fost batjocorită şi a rămas însărcinată. „Nu a putut trece peste acest lucru şi peste faptul că trebuia să aducă pe lume un copil nedorit. A mers în pădurea Radovan şi s-a spânzurat de o creangă. Mai târziu s-a dovedit că fata nu era gravidă .Toată lume spune că era foarte frumoasă, iar băieţii erau tot timpul în preajma ei“, a povestit un localnic pnetru „Adevărul”.  Şoferii care trec prin pădurea Radovan sunt sfătuiţi să nu încetinească sau să se uite în altă parte decât înainte."));
        objsList.add(new Obiect("Dealul Lunganilor, Iaşi ", R.drawable.lu3,"Localnicii sunt îngroziţi de zeci de ani de ceea ce numesc ei fantomele a peste 1.000 de soldaţi români morţi pe dealul Lunganilor în 1916, în timpul celui De-al Doilea Război Mondial. Se spune că acolo s-au dat bătălii crâncene, că armata română a fost blocată şi că mulţi soldaţi au murit de tifos şi au fost îngropaţi apoi la repezeală în gropi comune. Întâmpările de care povestesc oamenii locului se petrec pe dealurile dintre satele Goeşti şi Brăeşti. Nu există om în vârstă care să nu aibă o poveste personală despre fantome şi stafii. Majoritatea oamenilor spun că schelete în costume militare îi însoţesc în întuneric, după miezul nopţii, dacă se încumetă să parcugă pe jos distanţa de câţiva kilometri prin pustietate.\n" +
                "„Unii spun că e Necuratul, alţii spun că este lumina dumnezeiască. Îmi spuneau oamenii, de multe ori nici eu nu credeam. Dar am văzut cu ochii mei. Se vedea cum se plimba o lumină din deal în vale şi din vale în deal, pe dealul cimitirului\", a spus, pentru „Adevărul”, Mihai Amăriuţei, un localnic octogenar, fost primar al comunei, care l-a însoţit pe Mihail Sadoveanu în tinereţe. Misterul şi frica oamenilor de-a se mai aventura la miezul nopţii între cele două sate este amplificat şi de cimitirul amplasat pe dealul care leagă cele două sate. Localnicii spun că, după construirea unei biserici pe dealul Lunganilor, la mijlocul anilor '60, apariţiile fantomatice s-au mai diminuat.\n"));
        objsList.add(new Obiect("Palatul Parlamentului, Bucureşti ", R.drawable.lu4,"Legendele urbane spun că Palatul Parlamentului este bântuit de fantomele morţilor. Apar noaptea pe coridoarele celei mai mari construcţii din Europa, rup sigilii, fluieră sau fac să ţiuie sistemele de securitate. Personalul de noapte al clădirii povesteşte cum aceste fantome au început să-şi facă simţită prezenţa cu aproximativ 10 ani în urmă. „Anca” este una dintre ele. Potrivit relatărilor, năluca este o tânără de 20 de ani, cu o rochie de vară cu desen floral, care se arată doar personalului în uniformă şi cere ajutor.\n" +
                "nsăşi Anca Petrescu, arhitectul-şef al Casei Poporului, îşi aminteşte de unul dintre accidente, în care o fată şi-a pierdut viaţa. „S-a dezechilibrat şi s-a prăbuşit de la o înălţime de 16 metri. În total, au fost 10-15 accidente mortale, iar de fiecare dată când se întâmpla o tragedie, directorul coordonator era destituit. Am auzit şi eu despre legendele morţilor zidiţi în pereţi, ba chiar la un moment dat se spunea că Piaţa Constituţiei este pavată cu cadavre ascunse. Aberant! După fiecare accident mortal se făcea o investigaţie militară şi cădeau capete de la nivel înalt pentru asta, a explicat arhitecta pentru adevarul.ro.\n"));
        objsList.add(new Obiect("Foişorul de foc, Bucureşti ", R.drawable.lu5,"Foişorul de Foc este o clădire de 42 metri înălţime din Bucureşti aflată între Obor, Calea Moşilor şi Nerva-Traian, mai precis: la intersecţia străzii Traian cu bulevardul Regele Ferdinand, în imediata apropiere a bisericii Oborul-Vechi. În trecut, servea drept turn de observaţie pentru apărarea împotriva incendiilor. A fost construit în 1890, la doi ani după ce precedentul turn, Turnul Colţei, ridicat în 1715, a fost demolat. Planurile au fost realizate de George Mandrea, în acea perioadă arhitectul-şef al Bucureştiului.\n" +
                "Foişorul de Foc a fost gândit a avea şi rolul de turn de apă. După finalizarea construcţiei, însă, compania locală de apă - Uzina de Apă Grozăveşti -nu a avut pompe suficient de puternice pentru a îl umple cu apă. Foişorul de Foc a fost folosit de către pompieri până în 1935, când şi-a pierdut rolul, întrucât în Bucureşti se ridicau tot mai multe clădiri înalte, iar introducerea telefoniei făcea inutilă existenţa unui turn de veghe. Din 1963, a fost transformat într-un Muzeu al Pompierilor. Există mai multe variante diferite asupra fenomenelor paranormale de aici: potrivit unora, în fiecare zi de 9, la orele 23,30, se aprind lumini. Alte legende vorbesc de fantoma unei soţii de pompier.\n"));
        objsList.add(new Obiect("Conacul Bellu, Urlaţi ", R.drawable.lu6,"Muzeul Conacul „Bellu” este un muzeu judeţean din Urlaţi, amplasat în str. Orzoaia de Sus nr. 2. Conacul Bellu este monument de arhitectură, construit în stil arhitectonic vechi românesc, la jumătatea secolului al XIX-lea. A fost casa familiei baron Alexandru Bellu. În 1926 familia Bellu a donat Academiei Române întreg complexul de clădiri aflat la Urlaţi. Din 1954 a funcţionat ca muzeu regional, până când a intrat în componenţa Complexului Muzeal Prahova. Din 1990 este în componenţa Muzeului Judeţean de Istorie şi Arheologie Prahova. Muzeul adăposteşte un patrimoniu mixt de artă plastică şi decorativă, etnografie (ceramică, ţesături, unelte, covoare româneşti din secolul al XIX-lea), cărţi rare în ediţii de lux, picturi din secolul al XIX-lea, faianţă, mobilier stil din diverse epoci, artă orientală şi extrem-orientală (vase şi stampe japoneze, vase de aramă, mobilier), icoane şi arme din secolele al XVIII-lea şi al XIX-lea.\n" +
                "Mobilierul expus a aparţinut aproape în totalitate familiei Bellu. Tot din colecţia Bellu sunt tablourile: Portret de bărbat de Pavel Dincovici, Ţărancă de Eugen Maximovici (1857-1926), Bătrân cerşetor de Theodor Aman, icoane, candelabre, sfeşnice, stampe japoneze şi vasele orientale, statuetă de bronz Venus din Milo - copie, un cap de copil din lut, un cap de satir din plumb, o casetă de farmacie, precum şi valoroase litografii realizate de Carol Popp de Szathmáry la jumătatea secolului al XIX-lea. Remarcabile sunt unele elemente arhitecturale precum: coloane şi capiteluri, chenare de uşi şi ferestre sculptate în piatră din veacurile al XVII-lea şi al XVIII-lea.\n" +
                "În urma poveştii despre un proprietar care s-a sinucis, construcţia a ajuns să fie considerată loc bântuit, localnicii numind-o „Casa Diavolului”. Ziua clădirea este normală, spun localnicii, dar noaptea se aud voci, paşi, precum şi pale de vânt care „trec” prin ziduri.\n"));
        objsList.add(new Obiect("Castelul Bran, Braşov ", R.drawable.lu7,"Un document emis de regele Ludovic I al Ungariei (1342-1382) la 17 noiembrie 1377, în Zvolen, le confirmă saşilor din Scaunul Braşovului (totaque communitas Saxonum sedis Brassouiensis) dreptul de a ridica, conform promisiunii, pe cheltuiala şi cu meşterii lor, o nouă cetate de piatră la Bran. Cu această ocazie, regele le promite braşovenilor că, dacă Ţara Românească va ajunge \"în mâinile noastre\", atunci vama va fi mutată de la Rucăr (Ruffa Arbor) la Bran. Referinţa din textul documentului din 1377 cu privire la o \"nouă cetate de piatră\" permite deducţia că fortificaţia de piatră, ce urma să fie edificată pe acest loc, a fost precedată de o întăritură de graniţă mai veche.\n" +
                "Această cetate, probabil din lemn, a fost ridicată de cavalerii teutoni între 1211-1225. Ea îi este atribuită magistrului Theodorikus. În secolul al XIII-lea, teritoriul cetăţii Bran a fost supus jurisdicţiei comitatului regal de Alba Iulia. În 1920, Consiliul Orăşenesc Braşov a donat castelul reginei Maria a României, în semn de recunoştinţă faţă de contribuţia sa la înfăptuirea Marii Uniri. La moartea reginei, în 1938, castelul a fost moştenit de către fiica sa preferată, principesa Ileana, căsătorită cu un membru al fostei familii imperiale de Habsburg. După 1948, Castelul Bran a fost naţionalizat şi a intrat în proprietatea statului român. Castelul a fost deschis vizitelor publice începând cu 1956, fiind amenajat ca muzeu de istorie şi artă feudală. În 1987, a intrat în restaurare, lucrare finalizată în linii mari în 1993. Castelul se redeschide ca muzeu şi reintră în circuitul turistic. La data de 1 iunie 2009, castelul intră pe deplin în posesia moştenitorilor Principesei Ileana: arhiducele Dominic de Habsburg, arhiducesa Maria Magdalena Holzhausen şi arhiducesa Elisabeta Sandhofer. Pe seama castelului circulă legenda că ar fi bântuit de Vlad Ţepeş şi de unele victime torturate de acesta. Povestea nu are, însă, niciun fel de susţinere istorică sau ştiinţifică.\n"));
        objsList.add(new Obiect("Mănăstirea Chiajna, Bucureşti", R.drawable.lu8,"Construcţia Mănăstirii Chiajna a început în timpul domniei lui Alexandru Vodă Ipsilanti (1774–1782) şi a fost finalizată în timpul domnului fanariot Nicolae Mavrogheni (1786–1790). A fost construită în stil neoclasic, având dimensiuni mari pentru acea vreme: 43 metri lungime şi 17 înălţime, ziduri groase de 1 şi 2 metri.\n" +
                "Urma să să fie unul dintre cele mai importante lăcaşuri de cult româneşti ale vremii, însă nu s-a întâmplat aşa. Legenda spune că biserica ar fi blestemată. Preoţii nu au slujit niciodată în ea, fiind bombardată de către turci chiar înainte de sfinţire. Aceştia crezuseră că acolo ar fi fost mai degrabă o cetate, şi din acest motiv au încercat să o distrugă. Astfel, toate actele ei au ars în întregime. Cu toate acestea, construcţia a rămas în picioare. Abia la cutremurul din 1977 s-a prăbuşit turla. Mănăstirea a fost părăsită pe timpul ciumei din vremea domniei lui Alexandru Ipsilanti. Alte surse susţin că mănăstirea funcţiona în 1792, dar a fost părăsită în vremea ciumei, când domnitor era Mihai Şuţu, după ce însuşi mitropolitul Ţării Româneşti, Cosma Popescu, a murit din această cauză chiar în această biserică. Legenda spune că aici se aud uneori sunete de clopote, deşi mănăstirea nu le mai are de peste două secole.\n"));
        objsList.add(new Obiect("Balta Vrăjitoarelor, Bucureşti ", R.drawable.lu9,"Povestea începe în satul Boldeşti, în Pădurea Boldu-Creţeasca. „Lângă Bucureşti, la doar 30 de minute distanţă de Pădurea Cernica, există o baltă blestemată, recunoscută şi temută inclusiv în prezent de localnici. Ascunsă în mijlocul pădurii Boldu-Creţeasca, balta este la prima vedere un banal ochi de apă de dimensiuni mai mult decât modeste, cu un diametru de doar cinci metri. În ciuda aparenţei obişnuite, se spune că peticul de apă este înconjurat de forţe din alte lumi şi este loc de manifestări inexplicabile“, se arată pe pagina de Facebook „Poveşti de groază”.\n" +
                "Se spune că balta a devenit cunoscută şi în rândul vrăjitoarelor care în preajma unor sărbători importante s-ar aduna în jurul bălţii. Se pare că orice vraja, blestem sau dezlegare spuse pe malul acestei bălţi se îndeplineşti negreşit. Unii localnici, se arată pe pagina de Facebook, ar fi văzut în jurul acestei bălţi mai multe fenomene ciudate, precum fulgere sau furtuni iscate din senin. Totodată, se spune că o mulţime de animale refuză să bea apă de aici, preferând să moară de sete în loc să guste apa din baltă. Pe lângă toate aceste poveşti iscate în jurul Bălţii Vrăjitoarelor, una este cu adevărat fascinantă. Se pare că balta nu ar avea fund. Desigur, spun specialiştii, toate acestea sunt doar poveşti născocite de oameni, de-a lungul vremii.\n"));


    }
}